-- SELECT * FROM customers;
-- Q1. What is the total revenue generated by male vs. female customers?
select
  "Gender",
  SUM("Purchase Amount (USD)") as total_revenue
from
  customers
group by
  "Gender";

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select
  *
from
  customers
where
  "Discount Applied" = 'yes'
  or "Discount Applied" = 'Yes'
  and "Purchase Amount (USD)" > (
    select
      AVG("Purchase Amount (USD)")
    from
      customers
  );

-- Q3. Which are the top 5 products with the highest average review rating?
select
  "Item Purchased" as product,
  AVG("Review Rating") as avg_rating,
  COUNT(*) as reviews_count
from
  customers
where
  "Review Rating" is not null
group by
  "Item Purchased"
order by
  avg_rating desc,
  reviews_count desc
limit
  5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select
  "Shipping Type" as shipping_type,
  AVG("Purchase Amount (USD)") as avg_purchase,
  COUNT(*) as orders_count,
  SUM("Purchase Amount (USD)") as total_revenue
from
  customers
where
  "Shipping Type" is not null
group by
  "Shipping Type"
order by
  avg_purchase desc;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select
  case
    when LOWER("Subscription Status") in ('yes', 'subscribed', 'true', '1') then 'subscribed'
    when "Subscription Status" is null
    or TRIM("Subscription Status") = '' then 'unknown'
    else 'not_subscribed'
  end as subscription_group,
  AVG("Purchase Amount (USD)") as avg_purchase,
  SUM("Purchase Amount (USD)") as total_revenue,
  COUNT(*) as customers_count
from
  customers
group by
  subscription_group
order by
  subscription_group;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select
  "Item Purchased" as product,
  COUNT(*) filter (
    where
      LOWER("Discount Applied") in ('yes', 'y', 'true', '1')
  )::numeric as discounted_count,
  COUNT(*)::numeric as total_count,
  ROUND(
    100.0 * COUNT(*) filter (
      where
        LOWER("Discount Applied") in ('yes', 'y', 'true', '1')
    ) / NULLIF(COUNT(*), 0),
    2
  ) as pct_discounted
from
  customers
group by
  "Item Purchased"
order by
  pct_discounted desc,
  total_count desc
limit
  5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with
  segments as (
    select
      case
        when COALESCE("Previous Purchases", 0) = 0 then 'New'
        when COALESCE("Previous Purchases", 0) between 1 and 4  then 'Returning'
        else 'Loyal'
      end as loyalty_segment,
      COUNT(*) as customers_count
    from
      customers
    group by
      1
  )
select
  *
from
  segments
order by
  case loyalty_segment
    when 'New' then 1
    when 'Returning' then 2
    when 'Loyal' then 3
  end;

--Q8. What are the top 3 most purchased products within each category?
select
  category,
  product,
  purchases
from
  (
    select
      "Category" as category,
      "Item Purchased" as product,
      COUNT(*) as purchases,
      ROW_NUMBER() over (
        partition by
          "Category"
        order by
          COUNT(*) desc,
          "Item Purchased"
      ) as rn
    from
      customers
    group by
      "Category",
      "Item Purchased"
  ) t
where
  rn <= 3
order by
  category,
  purchases desc;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
with
  buyer_groups as (
    select
      case
        when COALESCE("Previous Purchases", 0) > 5 then 'repeat_buyer'
        else 'not_repeat'
      end as buyer_type,
      "Subscription Status"
    from
      customers
  )
select
  buyer_type,
  COUNT(*) as total_customers,
  COUNT(*) filter (
    where
      LOWER("Subscription Status") in ('yes', 'subscribed', 'true', '1')
  ) as subscribed_count,
  ROUND(
    100.0 * COUNT(*) filter (
      where
        LOWER("Subscription Status") in ('yes', 'subscribed', 'true', '1')
    ) / NULLIF(COUNT(*), 0),
    2
  ) as pct_subscribed
from
  buyer_groups
group by
  buyer_type
order by
  buyer_type;

--Q10. What is the revenue contribution of each age group?
select
  age_group,
  SUM("Purchase Amount (USD)") as revenue,
  ROUND(
    100.0 * SUM("Purchase Amount (USD)") / NULLIF(
      (
        select
          SUM("Purchase Amount (USD)")
        from
          customers
      ),
      0
    ),
    2
  ) as pct_of_total_revenue,
  COUNT(*) as purchases_count
from
  (
    select
      "Purchase Amount (USD)",
      case
        when "Age" is null then 'unknown'
        when "Age" < 25 then '<25'
        when "Age" between 25 and 34  then '25-34'
        when "Age" between 35 and 44  then '35-44'
        when "Age" between 45 and 54  then '45-54'
        when "Age" between 55 and 64  then '55-64'
        else '65+'
      end as age_group
    from
      customers
  ) s
group by
  age_group
order by
  -- order groups logically: unknown last
  case
    when age_group = '<25' then 1
    when age_group = '25-34' then 2
    when age_group = '35-44' then 3
    when age_group = '45-54' then 4
    when age_group = '55-64' then 5
    when age_group = '65+' then 6
    else 99
  end;
